@Warehouse.Api_HostAddress = https://localhost:7054

### BasketController

### Create BasketLine
POST {{Warehouse.Api_HostAddress}}/api/basket/
accept: */*
Content-Type: application/json

{
  "userId": "11111111-2222-2321-2321-111111111456",
  "basketLine": {
    "productId": "b3d2941b-d39c-4719-a7e6-2361bd15b67b",
    "sizeId": "33333333-3333-3333-3333-333333333333",
    "quantity": 2,
    "price": 10
  }
}


### Delete BasketLine
### Parameter: basketLineId
DELETE {{Warehouse.Api_HostAddress}}/api/basket/basketLines/EFA2E5C8-1958-45F2-B096-08DC33825022

### Bulk Delete BasketLines
### Parameter: UserId 
DELETE {{Warehouse.Api_HostAddress}}/api/Basket/11111111-2222-2321-2321-111111111456

### Update BasketLine
### Parameter: BasketLineId
PUT {{Warehouse.Api_HostAddress}}/api/basket/basketLines/20226947-6480-41E9-2C3F-08DC33830374
Content-Type: application/json

{
  "sizeId": "44444444-4444-4444-4444-444444444444",
  "quantity": 10
}
